### ISSUE TITLE
GIB LINK

### ISSUE THREAD

**Issue by Anogh297** [DragonWorldDiscord/Website#1]
I wanna visit this very secret website so GIB LINK

**Comment by NightZan999** [comment]
?

**Comment by NightZan999** [comment]
Currently **the old version is on: https://nightzan.com/server and I didn't bother getting SSL. Plus ignore the damn navbar**
Once I make the website ~~more static~~ much better and then get the content, then we'll talk 👍🏻

**Comment by NightZan999** [comment]
I'm planning to use a frontend framework like react to help with our website!

**Comment by NightZan999** [comment]
Thus I'll have to revamp the entire thing anyways.
